/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package guessgame.server;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

public class App {

    public static final int SERVER_PORT = 9999;

    public static void main(String[] args) {
        
        try (ServerSocket serverSocket = new ServerSocket(SERVER_PORT);) {
            System.out.println("Server is up an running...");
            
            while (true) {
                new GameThread(socket.accept()).start();

            }
            
        }
        catch (IOException e) {
            System.out.println("Server run into a IOException!");
        }
    }
}
